homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction: 

# Enables the frontend
frontend:

# Enables configuration UI
config:
#http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
#sun:

# Weather prediction

# Text to speech
tts:
  - platform: google


sensor:
  - platform: mitemp_bt 
    mac: '4C:65:A8:D3:9F:46' #工厂小米温湿度计
    name: 温湿度
    force_update: false
    median: 3
    monitored_conditions:
      - temperature
      - humidity

switch:
  - platform: chuangmi_ir
    name: "办公室"
    host:  192.168.1.228
    token: 364a603cd596d39e674f97badf430830
    switches:
      reciever:
        command_on: Z6VHAC4CAACiBgAArwgAALsRAAA+IwAAVKEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQEAAAEAAQABAAABAQAAAQABAAAAAAEAAQABAQEBBQJAA=
        command_off: Z6VHAC4CAACiBgAArwgAALsRAAA+IwAAVKEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQEAAAEAAQABAAABAQAAAQABAAAAAAEAAQABAQEBBQJAA=

# hair_air:Z6XlACwCAABjBgAA0AsAAEMRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiMhAAEAAAEBAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEBAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAQABAQEAAQEBAA
# letv:Z6VHAC4CAACiBgAArwgAALsRAAA+IwAAVKEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQEAAAEAAQABAAABAQAAAQABAAAAAAEAAQABAQEBBQJAA=
# Device ID: 88224799
#Model info: chuangmi.ir.v2
#Address: 192.168.1.228
#Token: 364a603cd596d39e674f97badf430830 via auto-token
#Support: At least generic
 
linptech_dongle:
  device: /dev/ttyUSB0

light:
  - platform: linptech_bulb
    id: 8000524B
    name: b3
  - platform: linptech_bulb
    name: b1
    id: 80005103
  - platform: linptech_bulb
    id: 800050EC
    name: b2
  - platform: linptech_bulb
    id: 80004E71
    name: b5
  - platform: linptech_bulb
    id: 80005016
    name: b4
  - platform: linptech_bulb
    id: 8000468A
    name: b7
  - platform: linptech_bulb
    id: 8000513D
    name: b6

# Cloud
# cloud:

# floorplan
panel_custom:
  - name: floorplan
    sidebar_title: 平面图
    sidebar_icon: mdi:home
    config: !include floorplan.yaml


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
