homeassistant:
  name: 领普科技
  # 经纬度
  latitude: 30.4418011306
  longitude: 114.4398800908
  # 海拔
  elevation: 0
  unit_system: metric
  time_zone: Asia/Shanghai
  customize: !include customize.yaml

  # linptech的灯控配置
  packages: !include_dir_named packages

config:
system_health:


http:
  api_password: !secret http_password

# Enables support for tracking state changes over time
history:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# homekit
homekit:

# hass性能
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use

ffmpeg:
  # ffmpeg_bin: '/Users/yangzhan/anaconda3/bin/ffmpeg' #macos
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: ffmpeg
    name: c1  #此为可选项，用于设定摄像头在Home Assistant中显示的名称
    input: rtsp://192.168.1.162:8854/live1.264?user=admin&passwd=
  - platform: ffmpeg
    name: c2  #此为可选项，用于设定摄像头在Home Assistant中显示的名称
    input: rtsp://192.168.1.162:8854/live2.264?user=admin&passwd= 

# binary_sensor:
#   - platform: ffmpeg_motion  #指定传感器工作平台为移动监测
#     name: menkou
#     input: rtsp://192.168.1.162:8854/live2.264?user=admin&passwd= 


climate:
  - platform: xiaomi_miio_airconditioningcompanion
    name: ac1
    host: 192.168.1.194
    token: 00ba936b166df35f664cb4ded9692d52
    target_sensor: sensor.temperature_158d0001f53706
    scan_interval: 60

      
# floorplan
panel_custom:
  - name: floorplan
    sidebar_title: 平面图
    sidebar_icon: mdi:home
    config: !include floorplan.yaml




