      name: Demo Floorplan
      image: /local/custom_ui/floorplan/floorplan.svg
      stylesheet: /local/custom_ui/floorplan/floorplan.css
      
      # These options are optional
      warnings:                  # enable warnings (to find out why things might ot be working correctly)
      # pan_zoom:                  # enable experimental panning / zooming
      # hide_app_toolbar:          # hide the application toolbar (when used as a custom panel)
      date_format: DD-MMM-YYYY   # Date format to use in hover-over text
      
      last_motion_entity: sensor.template_last_motion
      last_motion_class: last-motion

      groups:
        - name: Lights
          entities:
             - light.r1
             - light.r2
             - light.r3
             - light.r4
             - light.r5
             - light.r6
             - light.r7
             - light.r8
             - light.r9
             - light.r10
             - light.r11
             - light.r12
             - light.r13
             - light.r14
             - light.r15
             - light.r16
             - light.r17
             - light.r18
             - light.r19

          states:
            - state: 'on'
              class: 'light-on'
            - state: 'off'
              class: 'light-off'
          action:
            domain: homeassistant   # This optional parameter allows you to use other services such as homeassistant.toggle like here.
            service: toggle
        
        - name: Cameras
          entities:
            - camera.c1
            - camera.c2
          states:
            - state: 'idle'
              class: 'camera-idle'
        
        - name: Climate
          entities:
            - climate.aqara_air_conditioning_companion
          states:
            - state: 'heat'
              class: 'light-on'
            - state: 'cool'
              class: 'light-on'
            - state: 'auto'
              class: 'light-on'
            - state: 'off'
              class: 'light-off'
          
        - name: Scripts
          entities:
            - script.off_work
          action:
            domain: script
            service: turn_on
