###################################################设备#######################
linptech_net:
  # device: /dev/tty.SLAB_USBtoUART  #macos
  device: /dev/ttyS0  # raspberry pi
  #device: COM3  # windows

light:
  - platform: linptech_receiver
    id: 800175fa
    name: r1 #会议室过道
    type: "81"
    channel: "01"
  - platform: linptech_receiver
    id: 800020f6
    name: r2 #展厅过道
    type: "81"
    channel: "01"
  
  - platform: linptech_receiver
    id: 80017677
    name: logo #展厅过道
    type: "81"
    channel: "01"
  
  # 周飞办公室
  - platform: linptech_receiver
    id: 80003f7d
    name: r3 
    type: "81"
    channel: "01" 
  # - platform: linptech_receiver
  #   id: 8000370a
  #   name: r4
  #   type: "81"
  #   channel: "01"
  
   




# switch:
#   # 发射器ID容器
#   - platform: linptech_transmitor



