###################################################设备#######################
linptech_dongle:
  device: /dev/tty.SLAB_USBtoUART
  #device: /dev/ttyS0
  #device: COM3

light:
  #办公室
  - platform: linptech_receiver
    id: 80017337
    name: 1

  #四路测试
  - platform: linptech_receiver
    id: 80012351
    name: 2
    type: "84"
    channel: "01"
  - platform: linptech_receiver
    id: 80012351
    name: 3
    type: "84"
    channel: "02"
  - platform: linptech_receiver
    id: 80012351
    name: 4
    type: "84"
    channel: "04"
  - platform: linptech_receiver
    id: 80012351
    name: 5
    type: "84"
    channel: "08"




